name: chatweb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flushbar: ^1.10.4
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  google_sign_in: ^4.4.6
  provider: ^4.1.1
  flutter_auth_buttons: ^0.8.0
  cloud_firestore: ^0.14.1+2
  shared_preferences: ^0.5.12



 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/

